
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "ABSTRACT AND ARROW AS ASSIGN BASE BIN_NUMBER BITAND BITNOT BITOR BITXOR BOOL BREAK BYTE CASE CATCH CHAR CHAR_LITERAL CHECKED CLASS COLON COMMA CONST CONTINUE DATE_LITERAL DECIMAL DECREMENT DEFAULT DELEGATE DIVIDE DIVIDE_ASSIGN DO DOT DOUBLE ELSE ENUM EQUALS EVENT EXPLICIT EXTERN FALSE FALSE_LITERAL FINALLY FIXED FLOAT FLOAT_LITERAL FOR FOREACH GE GOTO GT HEX_NUMBER ID IF IMPLICIT IN INCREMENT INT INTERFACE INTERNAL IS LBRACE LBRACKET LE LOCK LONG LPAREN LSHIFT LT MINUS MINUS_ASSIGN MOD MOD_ASSIGN NAMESPACE NEW NOT NOTEQUAL NULL NUMBER OBJECT OPERATOR OR OUT OVERRIDE PARAMS PLUS PLUS_ASSIGN PRIVATE PROTECTED PUBLIC QUESTION RBRACE RBRACKET READONLY REF RETURN RPAREN RSHIFT SBYTE SEALED SEMICOLON SHORT SIZEOF STACKALLOC STATIC STRING STRING_LITERAL STRUCT SWITCH THIS THROW TIMES TIMES_ASSIGN TRUE TRUE_LITERAL TRY TYPEOF UINT ULONG UNCHECKED UNSAFE USHORT USING VIRTUAL VOID VOLATILE WHILE XML_COMMENTexpression : expression '+' expression\n                  | expression '-' expression\n                  | expression '*' expression\n                  | expression '/' expressionexpression : '(' expression ')' expression : NUMBER\n                  | HEX_NUMBER\n                  | BIN_NUMBER expression : STRING_LITERALexpression : CHAR_LITERALexpression : TRUE_LITERAL\n                  | FALSE_LITERAL"
    
_lr_action_items = {'(':([0,2,10,11,12,13,],[2,2,2,2,2,2,]),'NUMBER':([0,2,10,11,12,13,],[3,3,3,3,3,3,]),'HEX_NUMBER':([0,2,10,11,12,13,],[4,4,4,4,4,4,]),'BIN_NUMBER':([0,2,10,11,12,13,],[5,5,5,5,5,5,]),'STRING_LITERAL':([0,2,10,11,12,13,],[6,6,6,6,6,6,]),'CHAR_LITERAL':([0,2,10,11,12,13,],[7,7,7,7,7,7,]),'TRUE_LITERAL':([0,2,10,11,12,13,],[8,8,8,8,8,8,]),'FALSE_LITERAL':([0,2,10,11,12,13,],[9,9,9,9,9,9,]),'$end':([1,3,4,5,6,7,8,9,15,16,17,18,19,],[0,-6,-7,-8,-9,-10,-11,-12,-1,-2,-3,-4,-5,]),'+':([1,3,4,5,6,7,8,9,14,15,16,17,18,19,],[10,-6,-7,-8,-9,-10,-11,-12,10,10,10,10,10,-5,]),'-':([1,3,4,5,6,7,8,9,14,15,16,17,18,19,],[11,-6,-7,-8,-9,-10,-11,-12,11,11,11,11,11,-5,]),'*':([1,3,4,5,6,7,8,9,14,15,16,17,18,19,],[12,-6,-7,-8,-9,-10,-11,-12,12,12,12,12,12,-5,]),'/':([1,3,4,5,6,7,8,9,14,15,16,17,18,19,],[13,-6,-7,-8,-9,-10,-11,-12,13,13,13,13,13,-5,]),')':([3,4,5,6,7,8,9,14,15,16,17,18,19,],[-6,-7,-8,-9,-10,-11,-12,19,-1,-2,-3,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,10,11,12,13,],[1,14,15,16,17,18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression + expression','expression',3,'p_expression_binop','m_yacc.py',7),
  ('expression -> expression - expression','expression',3,'p_expression_binop','m_yacc.py',8),
  ('expression -> expression * expression','expression',3,'p_expression_binop','m_yacc.py',9),
  ('expression -> expression / expression','expression',3,'p_expression_binop','m_yacc.py',10),
  ('expression -> ( expression )','expression',3,'p_expression_group','m_yacc.py',23),
  ('expression -> NUMBER','expression',1,'p_expression_number','m_yacc.py',27),
  ('expression -> HEX_NUMBER','expression',1,'p_expression_number','m_yacc.py',28),
  ('expression -> BIN_NUMBER','expression',1,'p_expression_number','m_yacc.py',29),
  ('expression -> STRING_LITERAL','expression',1,'p_expression_string','m_yacc.py',33),
  ('expression -> CHAR_LITERAL','expression',1,'p_expression_char','m_yacc.py',37),
  ('expression -> TRUE_LITERAL','expression',1,'p_expression_boolean','m_yacc.py',41),
  ('expression -> FALSE_LITERAL','expression',1,'p_expression_boolean','m_yacc.py',42),
]
